title: Mesut Caliskan
email: your@email.com
description: >
  Theoretical physicist and cosmologist

author: Mesut Caliskan
baseurl: "" # leave empty for GitHub Pages root
url: "https://mesutcaliskan.github.io"

# Social Profiles (optional — fill or delete)
twitter_username: 
github_username: MesutCaliskan
facebook_username: 
instagram_username: 
linkedin_username: 

# Google Analytics (optional)
google_analytics: ""

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
